### ISSUE TITLE
Can you share the code to get the SemLM features?

### ISSUE THREAD

**Issue by Brandonnogithub** [nathlacroix/NLP-Adventures#13]
I run the code in the semLM file(parse_dataset.py). But the result is diffent from the files in annotations. Can you share how to get the annotations. thanks!

**Comment by sarlinpe** [comment]
We provide the semLM code as reference since this is experimental. I therefore can't provide support for that. Check that your Framenet SRL gives coherent predictions, the model might not be loading correctly.

**Comment by Brandonnogithub** [comment]
Ok, thanks.
